### ISSUE TITLE
Please add a screen shot so I can add this to awesome-zsh-plugins

### ISSUE THREAD

**Issue by unixorn** [iamskok/iamskok.zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

**Comment by iamskok** [comment]
@unixorn Added in [README.md](https://github.com/iamskok/iamskok.zsh-theme/blob/master/README.md). Thank you.

**Comment by unixorn** [comment]
Cool, added to [awesome-zsh-plugins](
https://github.com/unixorn/awesome-zsh-plugins)
